#!/bin/sh /etc/rc.common
# Copyright (C) 2015 wifisong.com
START=99
STOP=1

. /lib/functions/wifisong.sh
wtp_config=/etc/wtp/config

init() {
    sed -r -e "s/^routerId=.+/routerId=$(routerId)/" -e t -e "1 i\routerId=$(routerId)" -i $wtp_config
    sed -r -e "s/^secret=.+/secret=$(share_secret)/" -e t -e "2 i\secret=$(share_secret)" -i $wtp_config
}

start() {
    init
    wtp &
}

stop() {
    killall -9 wtp
}
