#!/bin/bash

# scan to enable the disappeared SSID in case
iw dev wlan0 scan

# RAM usage monitoring
tmpfsUsage=$(df | grep " /tmp" | awk '/.+/{ print $5}' | sed -r 's/([0-9]+)(%)/\1/')
if [ "$tmpfsUsage" -gt 80 ]; then
	logger -p user.warning -t "watchdog" "tmpfs usage is $tmpfsUsage percent"
fi
	
jffs2Usage=$(df | grep " /overlay" | awk '/.+/{ print $5}' | sed -r 's/([0-9]+)(%)/\1/')
if [ "$jffs2Usage" -gt 80 ]; then
	logger -p user.warning -t "watchdog" "jffs2 usage is $jffs2Usage percent"
fi
	
# CPU usage monitoring
	
# Process monitoring
process=$(ps | awk '/[w]tp/{print $1}')
if [[ -z $process ]]; then
	logger -p user.error -t "watchdog" "wtp process doesn't exist"
    wtp &
fi
	
process=$(ps | awk '/[s]tation/{print $1}')
if [[ -z $process ]]; then
	logger -p user.error -t "watchdog" "station process doesn't exist"
fi
	        
process=$(ps | awk '/[p]ktDump.sh/{print $1}')
if [[ -z $process ]]; then
	logger -p user.error -t "watchdog" "pktDump process doesn't exist"
fi
        
process=$(ps | awk '/[p]ktTrans.sh/{print $1}')
if [[ -z $process ]]; then
	logger -p user.error -t "watchdog" "pktTrans process doesn't exist"
fi
	
process=$(ps | awk '/[p]ktPostProcess/{print $1}')
if [[ -z $process ]]; then
	logger -p user.error -t "watchdog" "pktPostProcess process doesn't exist" 
fi
