#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org
# BASSFIRE@QQ
START=99

ibeacon_enable=$(uci get ibeacon.default.ibeacon_enable)
uuid=$(uci get ibeacon.default.uuid)
#major=$(uci get ibeacon.default.major)
#minor=$(uci get ibeacon.default.minor)
######MINOR######
inor=`printf %x $(uci get ibeacon.default.minor)`
a=`echo "$inor" |awk -F '' '{print $1}'`
b=`echo "$inor" |awk -F '' '{print $2}'`
c=`echo "$inor" |awk -F '' '{print $3}'`
d=`echo "$inor" |awk -F '' '{print $4}'`
#echo "$a"
if [ ! $d ] & [ ! $c ] & [ ! $b ]; then
  minor=`echo "00 0$a"`
  elif  [ ! $d ] & [ ! $c ]; then
  minor=`echo "00 $a$b"` 
  elif  [ ! $d ]; then
  minor=`echo "0$a $b$c"`
  else
  minor=`echo "$a$b $c$d"`   
fi
######MAJOR######
ajor=`printf %x $(uci get ibeacon.default.major)`
a=`echo "$ajor" |awk -F '' '{print $1}'`
b=`echo "$ajor" |awk -F '' '{print $2}'`
c=`echo "$ajor" |awk -F '' '{print $3}'`
d=`echo "$ajor" |awk -F '' '{print $4}'`
#echo "$a"
if [ ! $d ] & [ ! $c ] & [ ! $b ]; then
  major=`echo "00 0$a"`
  elif  [ ! $d ] & [ ! $c ]; then
  major=`echo "00 $a$b"` 
  elif  [ ! $d ]; then
  major=`echo "0$a $b$c"`
  else
  major=`echo "$a$b $c$d"`   
fi 

power=$(uci get ibeacon.default.power)

if      [ "$ibeacon_enable" -eq 1 ];then
         hciconfig hci0 up
         hciconfig hci0 noleadv
         hcitool -i hci0 cmd 0x08 0x0008 1e 02 01 1a 1a ff 4c 00 02 15 $uuid $major $minor $power 00
         hciconfig hci0 leadv
else 
         hciconfig hci0 noleadv
         hciconfig hci0 down
#echo "$major $minor">>/etc/1.txt
#echo "$date">>/etc/1.txt
fi



